# Generated by Django 3.2.16 on 2023-05-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user__username', 'following__username')},
        ),
    ]
